version: '3.7'

services:
  web:
    build: ./
    container_name: my_shop_web
    restart: always
    command: gunicorn my_shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - static_volume:/home/app/web/static
      - photos_volume:/home/app/web/photos
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: my_shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: my_shop_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
      - photos_volume:/home/app/web/photos
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  photos_volume: