# Generated by Django 4.1.1 on 2022-10-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_coupon_product_coupon_history_product_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coupon_history',
        ),
        migrations.AddField(
            model_name='profile',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.coupon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='coupon_history',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
