# Generated by Django 4.1.1 on 2022-10-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0020_alter_descriptionproductcart_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='history_of_buy',
        ),
    ]
