# Generated by Django 4.1.1 on 2022-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0026_alter_comments_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_in_the_cart',
            field=models.ManyToManyField(blank=True, null=True, through='shop_app.DescriptionProductCart', to='shop_app.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products_in_the_preferences',
            field=models.ManyToManyField(blank=True, null=True, to='shop_app.product'),
        ),
    ]
