# Generated by Django 4.1.1 on 2022-10-23 19:15

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Сategories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=150)),
                ("your_message", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "big_description_product",
                    models.TextField(blank=True, max_length=500),
                ),
                (
                    "small_description_product",
                    models.TextField(blank=True, max_length=500),
                ),
                ("price", models.FloatField()),
                ("price_for_what", models.CharField(max_length=20)),
                ("in_reality", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("photos", models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/")),
                ("tredemark", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=150)),
                ("count_in_reality", models.IntegerField(blank=True)),
                ("discount", models.IntegerField(blank=True, default=0)),
                ("avg_rating", models.IntegerField(blank=True, default=5)),
                ("count_comments", models.IntegerField(blank=True, default=0)),
                (
                    "category",
                    models.ForeignKey(
                        default="Others",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="shop_app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products_in_the_preferences",
                    models.ManyToManyField(blank=True, to="shop_app.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("count_of_buy", models.IntegerField(default=0)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("spent_money", models.FloatField(blank=True, null=True)),
                ("balance", models.FloatField(default=0)),
                (
                    "cart",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.cart",
                    ),
                ),
                (
                    "history_of_buy",
                    models.ManyToManyField(blank=True, to="shop_app.product"),
                ),
                (
                    "wish_list",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="shop_app.tag"),
        ),
        migrations.CreateModel(
            name="Compare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_to_compare",
                    models.ManyToManyField(blank=True, to="shop_app.product"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=150,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                ("description_comment", models.TextField(blank=True, max_length=500)),
                ("created_at_comment", models.DateTimeField(auto_now_add=True)),
                ("rating_products", models.IntegerField(default=5)),
                ("email", models.EmailField(max_length=254)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.product",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["profile"],
            },
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=150)),
                ("county", models.CharField(max_length=150)),
                ("postcode", models.CharField(max_length=150)),
                ("order_notes", models.TextField(max_length=300)),
                (
                    "cart",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.cart",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="products_in_the_basket",
            field=models.ManyToManyField(blank=True, to="shop_app.product"),
        ),
    ]
