# Generated by Django 4.1.1 on 2022-10-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0003_remove_cart_products_in_the_basket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("discount", models.IntegerField(blank=True, default=0)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="coupon_history",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop_app.coupon",
            ),
        ),
    ]
