# Generated by Django 4.1.1 on 2022-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_product_coupon_remove_product_coupon_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_product_in_cart',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='count_product_in_wish_list',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
