# Generated by Django 4.1.1 on 2022-10-26 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0008_remove_checkout_cart_checkout_product_to_buy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="order_notes",
        ),
    ]
