# Generated by Django 4.1.1 on 2022-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0009_remove_checkout_order_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
