# Generated by Django 4.1.1 on 2022-10-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_alter_checkout_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='number',
        ),
    ]
