# Generated by Django 4.1.1 on 2022-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0018_rename_tredemark_product_trademark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="price",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="comments",
            name="description_comment",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="descriptionproductcart",
            name="quality",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="profile",
            name="count_product_in_cart",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="count_product_in_wish_list",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="spent_money",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
